# Generated by Django 6.1.1 on 2026-09-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0003_moodentry_user_alter_moodentry_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
